name: First Workflow
#Workflow_dispatch means mannually triggering this job
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      -name: print greeting
      run: echo "hello runner"
      -name: print goodbye
      run: echo "Doon bye"
